### ISSUE TITLE
Cannot update to v1.1.1

### ISSUE THREAD

**Issue by amcneal-wt** [phrase/phraseapp-sketch#1] opened 2019-09-19 15:11 UTC
Sketch tells me v1.1.1 is available but the "Update" button does nothing. Downloading the plugin from https://phrase.com/sketch/ only downloads v1.1.0.

Also, v1.1.0 pops up the plugin window every time I export to Zeplin even after closing.

**Comment by theSoenke** [comment] 2019-09-19 15:55
@amcneal-wt Hi, thanks for reporting it. We have found the root cause for the version issue and will release a new version tomorrow to resolve it.

For the second issue we will have a closer look whether to reproduce it and get back to you when we have an update

**Comment by FRSgit** [comment] 2019-09-23 15:15
Hey @amcneal-wt,

Once again thank you for pointing this issues out - we have found a flaw in our release process and fixed it. I'm sorry that you had to wait until today to get this working, but because this one coincided with our release schedule we decided to release this fix altogether with version [1.1.2](https://github.com/phrase/phraseapp-sketch/releases/tag/1.1.2).

Can you confirm if the issue with "update button does nothing" went away?

And in connection with second problem - we are still working on changing list of events on which toolbar pops-up, but don't have any stable solution yet.

**Comment by amcneal-wt** [comment] 2019-09-23 15:40
Hey @FRSgit, the update button now works in the Plugins tab so I have the latest installed now. Thanks!

I'm seeing some slowness with the plugin and keys not updating in Sketch but they're not necessarily related to the original bug filed here so we can close this issue. If you or someone on the team is interested in helping me out though, we can sync up over Slack, email, or a quick call. It's basically unusable at the moment for me.

**Comment by FRSgit** [comment] 2019-09-23 16:02
Hey, yep, just hit me on the email jakub.freisler (at) phrase.com and we will figure out what's going on (we can call tomorrow's after 10.30 am, give me a sign if that suits you)

**Comment by FRSgit** [comment] 2019-09-23 16:03
Leaving opened as the Zeplin-related bug is still there

**Comment by FRSgit** [comment] 2020-02-06 11:30
Ah, forgot to reply here 😞
@amcneal-wt You should experience now no bugs related to plugin window opening itself too often (or after some actions, like exporting to Zeplin). Can you please check that out and respond if the issue got resolved? Thanks! ✌️

**Comment by amcneal-wt** [comment] 2020-02-07 14:22
Thanks for updating! I haven't seen any issues lately so looks like it's all resolved.

**Comment by FRSgit** [comment] 2020-02-07 15:45
@amcneal-wt Thanks for the quick response!
Glad I could help, don't hesitate to reach out to us whenever you come across any weird behaviour within our plugin 😉 

Then, if the error got resolved, I'm closing the issue.
Cheers!

**Closed as completed by FRSgit** 2020-02-07 15:45 UTC
